apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynlora-models
  namespace: dynamic-lora
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: svc-dyn
  namespace: dynamic-lora
spec:
  model:
    uri: hf://hmellor/tiny-random-LlamaForCausalLM
    name: model-dyn
  replicas: 1
  router:
    scheduler: {}
    gateway: {}
    route:
      http:
        spec:
          rules:
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/completions
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /dynamic-lora/svc-dyn/v1/completions
            name: v1-completions-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/chat/completions
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /dynamic-lora/svc-dyn/v1/chat/completions
            name: v1-chat-completions-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/responses
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /dynamic-lora/svc-dyn/v1/responses
            name: v1-responses-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/messages
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /dynamic-lora/svc-dyn/v1/messages
            name: v1-messages-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            matches:
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/chat/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/chat/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/responses
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/responses/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/messages
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: Exact
                value: /v1/messages/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/chat/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/chat/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/chat/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/chat/completions
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/chat/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/chat/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/chat/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/chat/completions/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/responses
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/responses
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/responses
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/responses
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/responses/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/responses/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/responses/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/responses/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/messages
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/messages
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/messages
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/messages
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: Exact
                value: /v1/messages/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: Exact
                value: /v1/messages/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: Exact
                value: /v1/messages/
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: Exact
                value: /v1/messages/
            name: v1-model-routing
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/completions
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /publishers/dynamic-lora/models/model-dyn/v1/completions
            name: v1-completions-publisher-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/chat/completions
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /publishers/dynamic-lora/models/model-dyn/v1/chat/completions
            name: v1-chat-completions-publisher-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/responses
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /publishers/dynamic-lora/models/model-dyn/v1/responses
            name: v1-responses-publisher-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: inference.networking.k8s.io
              kind: InferencePool
              name: svc-dyn-inference-pool
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /v1/messages
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /publishers/dynamic-lora/models/model-dyn/v1/messages
            name: v1-messages-publisher-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: ''
              kind: Service
              name: svc-dyn-kserve-workload-svc
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /publishers/dynamic-lora/models/model-dyn
            name: v1-publisher-path-catch-all
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: ''
              kind: Service
              name: svc-dyn-kserve-workload-svc
              port: 8000
              weight: 1
            filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  replacePrefixMatch: /
                  type: ReplacePrefixMatch
            matches:
            - path:
                type: PathPrefix
                value: /dynamic-lora/svc-dyn
            name: v1-catch-all-path
            timeouts:
              backendRequest: 0s
              request: 0s
          - backendRefs:
            - group: ''
              kind: Service
              name: svc-dyn-kserve-workload-svc
              port: 8000
              weight: 1
            matches:
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/model-dyn
              path:
                type: PathPrefix
                value: /
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-1
              path:
                type: PathPrefix
                value: /
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-2
              path:
                type: PathPrefix
                value: /
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-3
              path:
                type: PathPrefix
                value: /
            - headers:
              - name: X-Gateway-Model-Name
                type: Exact
                value: publishers/dynamic-lora/models/adapter-4
              path:
                type: PathPrefix
                value: /
            name: v1-catch-all-model-routing
            timeouts:
              backendRequest: 0s
              request: 0s
  template:
    volumes:
    - name: lora-store
      persistentVolumeClaim:
        claimName: dynlora-models
    containers:
    - name: main
      image: vllm/vllm-openai-cpu:v0.19.0
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      volumeMounts:
      - name: lora-store
        mountPath: /mnt/lora
      env:
      - name: VLLM_CPU_KVCACHE_SPACE
        value: '1'
      - name: VLLM_LOGGING_LEVEL
        value: INFO
      - name: VLLM_ADDITIONAL_ARGS
        value: --enable-lora --max-loras=4
      - name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
        value: '1'
      resources:
        requests:
          cpu: '2'
          memory: 4Gi
        limits:
          cpu: '8'
          memory: 12Gi
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 5
        timeoutSeconds: 5
        failureThreshold: 60
      startupProbe:
        httpGet:
          path: /health
          port: 8000
        periodSeconds: 10
        failureThreshold: 60
