apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llmisvc-epp
  namespace: controlled-deployment-spike
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: llminferenceservice-router-scheduler
  endpoints:
    - port: metrics
      interval: 10s
      authorization:
        credentials:
          name: metrics-reader-token
          key: token
