apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth-proxy-sa-inferenceservice-get
rules:
  - apiGroups:
      - serving.kserve.io
    resources:
      - inferenceservices
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth-proxy-sa-inferenceservice-get-binding
subjects:
  - kind: ServiceAccount
    name: oauth-proxy-sa
    namespace: kserve-model
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauth-proxy-sa-inferenceservice-get