apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-proxy-sa
  namespace: kserve-model
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauth-proxy-spike"}}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oauth-proxy-spike-auth-delegator
subjects:
- kind: ServiceAccount
  name: oauth-proxy-sa
  namespace: kserve-model
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth-proxy-sa-view
subjects:
- kind: ServiceAccount
  name: oauth-proxy-sa
  namespace: kserve-model
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view