apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: model-tiny-llama
  namespace: controlled-deployment-spike
spec:
  model:
    name: tiny-llama
    uri: "hf://hmellor/tiny-random-LlamaForCausalLM"
